name: Democracy Enforcer
description: Enforce democracy on a repository by merging pull requests by voting score.
author: deuzu

branding:
  icon: alert-octagon
  color: green

inputs:
  github-token:
    required: false
    description: The Github token that give permission on the repository.
    default: '${{ secret.GITHUB_TOKEN }}'

runs:
  using: node12
  main: dist/index.js
